artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/f3eea11418f94c44abcec04ae2a690e4/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: f3eea11418f94c44abcec04ae2a690e4
run_name: LGBMClassifier_param_set_0
run_uuid: f3eea11418f94c44abcec04ae2a690e4
source_name: ''
source_type: 4
source_version: ''
start_time: 1734600755561
status: 1
tags: []
user_id: unknown
