artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/d0d8b58baab04facabcf94de70f7f9f9/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: d0d8b58baab04facabcf94de70f7f9f9
run_name: CatBoostClassifier_param_set_0
run_uuid: d0d8b58baab04facabcf94de70f7f9f9
source_name: ''
source_type: 4
source_version: ''
start_time: 1734600758417
status: 1
tags: []
user_id: unknown
