artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/bf10fa1fec474addb0a82e3d259f3b56/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: bf10fa1fec474addb0a82e3d259f3b56
run_name: XGBClassifier_param_set_2
run_uuid: bf10fa1fec474addb0a82e3d259f3b56
source_name: ''
source_type: 4
source_version: ''
start_time: 1734600749928
status: 1
tags: []
user_id: unknown
