artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/083aa69c2a134acb8f2ca6cc1aa7a23d/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 083aa69c2a134acb8f2ca6cc1aa7a23d
run_name: CatBoostClassifier_test_4
run_uuid: 083aa69c2a134acb8f2ca6cc1aa7a23d
source_name: ''
source_type: 4
source_version: ''
start_time: 1734599359663
status: 1
tags: []
user_id: unknown
