artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/f4cb62a950c94918a64facfc5934ca4c/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: f4cb62a950c94918a64facfc5934ca4c
run_name: CatBoostClassifier_test_7
run_uuid: f4cb62a950c94918a64facfc5934ca4c
source_name: ''
source_type: 4
source_version: ''
start_time: 1734600587895
status: 1
tags: []
user_id: unknown
