artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/a7c19bd9f6dd4bb5970e2872b5bb67d9/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: a7c19bd9f6dd4bb5970e2872b5bb67d9
run_name: RandomForestClassifier_param_set_0
run_uuid: a7c19bd9f6dd4bb5970e2872b5bb67d9
source_name: ''
source_type: 4
source_version: ''
start_time: 1734599379186
status: 1
tags: []
user_id: unknown
