artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/9ba4d48f5f214f32a3bedbefd5fc581e/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 9ba4d48f5f214f32a3bedbefd5fc581e
run_name: LGBMClassifier_param_set_2
run_uuid: 9ba4d48f5f214f32a3bedbefd5fc581e
source_name: ''
source_type: 4
source_version: ''
start_time: 1734507871666
status: 1
tags: []
user_id: unknown
