artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/3b95a07eb0844b77acd120ddcbddbae4/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 3b95a07eb0844b77acd120ddcbddbae4
run_name: CatBoostClassifier_param_set_2
run_uuid: 3b95a07eb0844b77acd120ddcbddbae4
source_name: ''
source_type: 4
source_version: ''
start_time: 1734600761577
status: 1
tags: []
user_id: unknown
