artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/e8b4f232ddbc43c3a5e511ea975db51c/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: e8b4f232ddbc43c3a5e511ea975db51c
run_name: RandomForestClassifier_test_4
run_uuid: e8b4f232ddbc43c3a5e511ea975db51c
source_name: ''
source_type: 4
source_version: ''
start_time: 1734599359449
status: 1
tags: []
user_id: unknown
