artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/f88b71bd5ff749a9ba4459b07bace034/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: f88b71bd5ff749a9ba4459b07bace034
run_name: LGBMClassifier_test_3
run_uuid: f88b71bd5ff749a9ba4459b07bace034
source_name: ''
source_type: 4
source_version: ''
start_time: 1734510586825
status: 1
tags: []
user_id: unknown
