artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/03a5a1f4aaac4695a2cc907f5f073a0d/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 03a5a1f4aaac4695a2cc907f5f073a0d
run_name: CatBoostClassifier_test_2
run_uuid: 03a5a1f4aaac4695a2cc907f5f073a0d
source_name: ''
source_type: 4
source_version: ''
start_time: 1734508886264
status: 1
tags: []
user_id: unknown
