artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/63a03ee04cbb4b53be62b56bedc04dae/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 63a03ee04cbb4b53be62b56bedc04dae
run_name: LGBMClassifier_param_set_2
run_uuid: 63a03ee04cbb4b53be62b56bedc04dae
source_name: ''
source_type: 4
source_version: ''
start_time: 1734508898952
status: 1
tags: []
user_id: unknown
