artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/75fda69fbdfb4628bb9be278d27b5d47/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 75fda69fbdfb4628bb9be278d27b5d47
run_name: CatBoostClassifier_param_set_0
run_uuid: 75fda69fbdfb4628bb9be278d27b5d47
source_name: ''
source_type: 4
source_version: ''
start_time: 1734599394081
status: 1
tags: []
user_id: unknown
