artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/c9dbe8b7d39743df93ba8baf50bfee97/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: c9dbe8b7d39743df93ba8baf50bfee97
run_name: LGBMClassifier_param_set_0
run_uuid: c9dbe8b7d39743df93ba8baf50bfee97
source_name: ''
source_type: 4
source_version: ''
start_time: 1734599391249
status: 1
tags: []
user_id: unknown
