artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/6f80c52dc4aa40aeb633c96eda9a0ef8/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 6f80c52dc4aa40aeb633c96eda9a0ef8
run_name: LGBMClassifier_test_8
run_uuid: 6f80c52dc4aa40aeb633c96eda9a0ef8
source_name: ''
source_type: 4
source_version: ''
start_time: 1734600743156
status: 1
tags: []
user_id: unknown
