artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/87f2e0efd79c414698ece00cca7a5d4e/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 87f2e0efd79c414698ece00cca7a5d4e
run_name: CatBoostClassifier_param_set_1
run_uuid: 87f2e0efd79c414698ece00cca7a5d4e
source_name: ''
source_type: 4
source_version: ''
start_time: 1734510597208
status: 1
tags: []
user_id: unknown
