artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/dab205ece149461f8e4a1ae9d9d0cd04/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: dab205ece149461f8e4a1ae9d9d0cd04
run_name: XGBClassifier_param_set_0
run_uuid: dab205ece149461f8e4a1ae9d9d0cd04
source_name: ''
source_type: 4
source_version: ''
start_time: 1734600747908
status: 1
tags: []
user_id: unknown
