artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/684050ecdddc498fbe3cb2318f8d16e1/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 684050ecdddc498fbe3cb2318f8d16e1
run_name: XGBClassifier_param_set_0
run_uuid: 684050ecdddc498fbe3cb2318f8d16e1
source_name: ''
source_type: 4
source_version: ''
start_time: 1734510590856
status: 1
tags: []
user_id: unknown
