artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/169b1acd0f9b4fbcb77594a0f173ea79/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 169b1acd0f9b4fbcb77594a0f173ea79
run_name: RandomForestClassifier_test_3
run_uuid: 169b1acd0f9b4fbcb77594a0f173ea79
source_name: ''
source_type: 4
source_version: ''
start_time: 1734510586750
status: 1
tags: []
user_id: unknown
