artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/5d6dd2d3a3b74dbb86cc32ffaca938b5/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 5d6dd2d3a3b74dbb86cc32ffaca938b5
run_name: LGBMClassifier_param_set_2
run_uuid: 5d6dd2d3a3b74dbb86cc32ffaca938b5
source_name: ''
source_type: 4
source_version: ''
start_time: 1734600602887
status: 1
tags: []
user_id: unknown
