artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/0ba3c57af1b7415a9e0972d84ef77cec/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 0ba3c57af1b7415a9e0972d84ef77cec
run_name: LGBMClassifier_param_set_1
run_uuid: 0ba3c57af1b7415a9e0972d84ef77cec
source_name: ''
source_type: 4
source_version: ''
start_time: 1734599391250
status: 1
tags: []
user_id: unknown
