artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/ff6056ce3ba343dab3d8d3cb6e212738/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: ff6056ce3ba343dab3d8d3cb6e212738
run_name: LGBMClassifier_test_5
run_uuid: ff6056ce3ba343dab3d8d3cb6e212738
source_name: ''
source_type: 4
source_version: ''
start_time: 1734599379060
status: 1
tags: []
user_id: unknown
