artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/0536ba37ca2b4bbf878a2d6b41ea2cd6/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 0536ba37ca2b4bbf878a2d6b41ea2cd6
run_name: RandomForestClassifier_test_9
run_uuid: 0536ba37ca2b4bbf878a2d6b41ea2cd6
source_name: ''
source_type: 4
source_version: ''
start_time: 1734600839694
status: 1
tags: []
user_id: unknown
