artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/76adefdde6864df5a0a8e6907b58d708/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 76adefdde6864df5a0a8e6907b58d708
run_name: XGBClassifier_param_set_1
run_uuid: 76adefdde6864df5a0a8e6907b58d708
source_name: ''
source_type: 4
source_version: ''
start_time: 1734508889071
status: 1
tags: []
user_id: unknown
