artifact_location: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/0
creation_time: 1734507785341
experiment_id: '0'
last_update_time: 1734507785341
lifecycle_stage: active
name: Default
