artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/c25094ae2a3f43aaabb54df9b3db3c9f/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: c25094ae2a3f43aaabb54df9b3db3c9f
run_name: XGBClassifier_test_9
run_uuid: c25094ae2a3f43aaabb54df9b3db3c9f
source_name: ''
source_type: 4
source_version: ''
start_time: 1734600839809
status: 1
tags: []
user_id: unknown
