artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/d4b0cec1e6314c73816f2b2afaca09be/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: d4b0cec1e6314c73816f2b2afaca09be
run_name: LGBMClassifier_test_9
run_uuid: d4b0cec1e6314c73816f2b2afaca09be
source_name: ''
source_type: 4
source_version: ''
start_time: 1734600839928
status: 1
tags: []
user_id: unknown
