artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/1c9d15cbf9bd4e249d053ea04bb0b24a/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 1c9d15cbf9bd4e249d053ea04bb0b24a
run_name: CatBoostClassifier_param_set_2
run_uuid: 1c9d15cbf9bd4e249d053ea04bb0b24a
source_name: ''
source_type: 4
source_version: ''
start_time: 1734599397446
status: 1
tags: []
user_id: unknown
