artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/aef3a20cfcba4ea19157932ce27f62e7/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: aef3a20cfcba4ea19157932ce27f62e7
run_name: XGBClassifier_param_set_1
run_uuid: aef3a20cfcba4ea19157932ce27f62e7
source_name: ''
source_type: 4
source_version: ''
start_time: 1734600747909
status: 1
tags: []
user_id: unknown
