artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/6dcb62d38d104dae8014eaa0c07c5a0e/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 6dcb62d38d104dae8014eaa0c07c5a0e
run_name: LGBMClassifier_param_set_0
run_uuid: 6dcb62d38d104dae8014eaa0c07c5a0e
source_name: ''
source_type: 4
source_version: ''
start_time: 1734507870318
status: 1
tags: []
user_id: unknown
