artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/c57a9edd228247ae82a543fea12b6f4e/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: c57a9edd228247ae82a543fea12b6f4e
run_name: XGBClassifier_param_set_2
run_uuid: c57a9edd228247ae82a543fea12b6f4e
source_name: ''
source_type: 4
source_version: ''
start_time: 1734599504385
status: 1
tags: []
user_id: unknown
