artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/a26bf1817f6d41e3af299ad4bd2375ca/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: a26bf1817f6d41e3af299ad4bd2375ca
run_name: RandomForestClassifier_test_8
run_uuid: a26bf1817f6d41e3af299ad4bd2375ca
source_name: ''
source_type: 4
source_version: ''
start_time: 1734600742952
status: 1
tags: []
user_id: unknown
