mlflow:
  tracking_uri: "http://127.0.0.1:8000"
  experiment_name: "handwriten-digit-recognition"
optuna:
  n_trials: 3
  n_jobs: 2
models:
  model_1:
    library: "sklearn"
    model_class: "RandomForestClassifier"
    model_params:
      n_jobs: 2
      n_estimators:
        param_type: "int"
        param_range: [50, 100]
      criterion:
        param_type: "categorical"
        param_range: ["gini", "entropy", "log_loss"]
      max_depth:
        param_type: "int"
        param_range: [2, 10]
      ccp_alpha:
        param_type: "float"
        param_range: [0.0, 0.5]
      max_features: "sqrt"
      random_state: 30
  model_2:
    library: "xgboost"
    model_class: "XGBClassifier"
    model_params:
      n_estimators:
        param_type: "int"
        param_range: [10,20]
      booster:
        param_type: "categorical"
        param_range: ["gbtree", "gblinear"]
      learning_rate:
        param_type: "float"
        param_range: [0.08,0.15]
      early_stopping_rounds: 5
      verbosity: 0
      n_jobs: 2
      random_state: 40
  model_3:
    library: "lightgbm"
    model_class: "LGBMClassifier"
    model_params:
      n_estimators:
        param_type: "int"
        param_range: [10,20]
      boosting_type:
        param_type: "categorical"
        param_range: ["gbdt", "dart"]
      learning_rate:
        param_type: "float"
        param_range: [0.08,0.15]
      max_depth: 3
      objective: "multiclass"
      verbosity: -1
      n_jobs: 2
      random_state: 50
  model_4:
    library: "catboost"
    model_class: "CatBoostClassifier"
    model_params:
      learning_rate:
        param_type: "float"
        param_range: [0.08,0.15]
      iterations: 5
      loss_function: "MultiClass"
      early_stopping_rounds: 2
      verbose: False
      allow_writing_files: False