mlflow:
  tracking_uri: "http://127.0.0.1:8000"
  experiment_name: "handwritten-digit-recognition"
optuna:
  n_trials: 2
  n_jobs: -1
models:
  model_1:
    library: "sklearn"
    model_class: "RandomForestClassifier"
    model_params:
      n_jobs: -1
      n_estimators:
        param_type: "int"
        param_range: [80, 120]
      criterion:
        param_type: "categorical"
        param_range: ["gini", "entropy", "log_loss"]
      max_depth:
        param_type: "int"
        param_range: [6, 20]
      ccp_alpha:
        param_type: "float"
        param_range: [0.0, 0.1]
      max_features: "sqrt"
      random_state: 30
  model_2:
    library: "xgboost"
    model_class: "XGBClassifier"
    model_params:
      n_estimators:
        param_type: "int"
        param_range: [80, 120]
      learning_rate:
        param_type: "float"
        param_range: [0.1, 0.3]
      max_depth:
        param_type: "int"
        param_range: [6, 20]
      early_stopping_rounds: 5
      verbosity: 0
      n_jobs: -1
      random_state: 40
  model_3:
    library: "lightgbm"
    model_class: "LGBMClassifier"
    model_params:
      n_estimators:
        param_type: "int"
        param_range: [80, 120]
      learning_rate:
        param_type: "float"
        param_range: [0.1, 0.3]
      max_depth:
        param_type: "int"
        param_range: [6, 20]
      objective: "multiclass"
      verbosity: -1
      n_jobs: -1
      random_state: 50
  model_4:
    library: "catboost"
    model_class: "CatBoostClassifier"
    model_params:
      learning_rate:
        param_type: "float"
        param_range: [0.01, 0.3]
      iterations:
        param_type: "int"
        param_range: [80, 120]
      depth:
        param_type: "int"
        param_range: [6, 16]
      loss_function: "MultiClass"
      early_stopping_rounds: 5
      verbose: False
      allow_writing_files: False
  model_5:
    library: "sklearn"
    model_class: "AdaBoostClassifier"
    model_params:
      n_estimators:
        param_type: "int"
        param_range: [50, 120]
      learning_rate:
        param_type: "float"
        param_range: [0.5, 1.5]
      random_state: 42
  model_6:
    library: "sklearn"
    model_class: "GradientBoostingClassifier"
    model_params:
      n_estimators:
        param_type: "int"
        param_range: [80, 120]
      criterion:
        param_type: "categorical"
        param_range: ["friedman_mse", "squared_error"]
      max_depth:
        param_type: "int"
        param_range: [3, 20]
      ccp_alpha:
        param_type: "float"
        param_range: [0.0, 0.1]
      learning_rate:
        param_type: "float"
        param_range: [0.1, 0.3]
      max_features: "sqrt"
      random_state: 42
  model_7:
    library: "sklearn"
    model_class: "SGDClassifier"
    model_params:
      penalty:
        param_type: "categorical"
        param_range: ["l2", "l1", "elasticnet"]
      loss:
        param_type: "categorical"
        param_range: ["hinge", "log_loss"]
      alpha:
        param_type: "float"
        param_range: [0.0001, 0.001]
      n_jobs: -1
      random_state: 42