library: "xgboost"
model_class: "XGBClassifier"
model_params:
    n_estimators: 10
    booster: "gblinear"
    learning_rate: 0.14
    early_stopping_rounds: 5
    verbosity: 0
    n_jobs: 2
    random_state: 40