artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/e01dbdbb3f9c4d428c3913c9cb063c0c/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: e01dbdbb3f9c4d428c3913c9cb063c0c
run_name: CatBoostClassifier_param_set_1
run_uuid: e01dbdbb3f9c4d428c3913c9cb063c0c
source_name: ''
source_type: 4
source_version: ''
start_time: 1734508510307
status: 1
tags: []
user_id: unknown
