artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/f940d58d2bc54f119cc7b3fdf2f7b910/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: f940d58d2bc54f119cc7b3fdf2f7b910
run_name: XGBClassifier_param_set_1
run_uuid: f940d58d2bc54f119cc7b3fdf2f7b910
source_name: ''
source_type: 4
source_version: ''
start_time: 1734510590857
status: 1
tags: []
user_id: unknown
