artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/e0257c02fafe4647a384409edb1d0f0c/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: e0257c02fafe4647a384409edb1d0f0c
run_name: RandomForestClassifier_param_set_2
run_uuid: e0257c02fafe4647a384409edb1d0f0c
source_name: ''
source_type: 4
source_version: ''
start_time: 1734510587444
status: 1
tags: []
user_id: unknown
