artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/38fd57cd84524d7bb05fbb6c2ef3438d/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 38fd57cd84524d7bb05fbb6c2ef3438d
run_name: LGBMClassifier_param_set_2
run_uuid: 38fd57cd84524d7bb05fbb6c2ef3438d
source_name: ''
source_type: 4
source_version: ''
start_time: 1734600757003
status: 1
tags: []
user_id: unknown
