artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/d2a4b22d4b004ca09fc46bd46b0f7d0e/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: d2a4b22d4b004ca09fc46bd46b0f7d0e
run_name: CatBoostClassifier_param_set_0
run_uuid: d2a4b22d4b004ca09fc46bd46b0f7d0e
source_name: ''
source_type: 4
source_version: ''
start_time: 1734508900139
status: 1
tags: []
user_id: unknown
