artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/ac2061a6fd2345abb9406dc7ee7ad182/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: ac2061a6fd2345abb9406dc7ee7ad182
run_name: XGBClassifier_test_4
run_uuid: ac2061a6fd2345abb9406dc7ee7ad182
source_name: ''
source_type: 4
source_version: ''
start_time: 1734599359549
status: 1
tags: []
user_id: unknown
