artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/0cd1a32dbf964d3cbdde0545a93084ca/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: 0cd1a32dbf964d3cbdde0545a93084ca
run_name: CatBoostClassifier_default_test
run_uuid: 0cd1a32dbf964d3cbdde0545a93084ca
source_name: ''
source_type: 4
source_version: ''
start_time: 1734507872734
status: 1
tags: []
user_id: unknown
