artifact_uri: /home/ano/projects/ML/handwriten-digit-recognition/127.0.0.1:8000/910887139536251208/f42b97ab0f8445ab84ce78371c0c3ca2/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910887139536251208'
lifecycle_stage: active
run_id: f42b97ab0f8445ab84ce78371c0c3ca2
run_name: RandomForestClassifier_param_set_0
run_uuid: f42b97ab0f8445ab84ce78371c0c3ca2
source_name: ''
source_type: 4
source_version: ''
start_time: 1734508886294
status: 1
tags: []
user_id: unknown
